const menu = [
  
  {
    id: 1,
    title: 'Chicken',
    category: 'lunch',
    price: 13,
    image: 'food/chicken.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 2,
    title: 'Coconut',
    category: 'Fruits',
    price: 6,
    image: 'food/coconut.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 3,
    title: 'FreshApple',
    category: 'breakfast',
    price: 15,
    image: 'food/freshApple.webp',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.',
  },
  {
    id: 4,
    title: 'Veggies',
    category: 'lunch',
    price: 650,
    image: 'food/noodle.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 5,
    title: 'Tikka',
    category: 'lunch',
    price: 220,
    image: 'food/tikka.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas. `,
  },
  {
    id: 6,
    title: 'Orange',
    category: 'Fruits',
    price: 19,
    image: 'food/orange.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 7,
    title: 'Mussel',
    category: 'lunch',
    price: 150,
    image: 'food/Mussel.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 8,
    title: 'Chicken wings',
    category: 'lunch',
    price: 60,
    image: 'food/meal.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 9,
    title: 'Banana',
    category: 'Fruits',
    price: 30,
    image: 'food/banaba.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 10,
    title: 'Noodle',
    category: 'breakfast',
    price: 90,
    image: 'food/healthyFood.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 11,
    title: 'Berry',
    category: 'Fruits',
    price: 30,
    image: 'food/berry.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 12,
    title: 'Pizza',
    category: 'lunch',
    price: 200,
    image: 'food/pizza.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 13,
    title: 'Leafy Vegitable',
    category: 'breakfast',
    price: 40,
    image: 'food/Carrot.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 14,
    title: 'Guvava Shake',
    category: 'Fruits',
    price: 16,
    image: 'food/guvava.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 15,
    title: 'Eggos',
    category: 'breakfast',
    price: 44,
    image: 'food/eggos.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 16,
    title: 'Meat',
    category: 'breakfast',
    price: 109,
    image: 'food/meat.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
  {
    id: 17,
    title: 'Papaya',
    category: 'Fruits',
    price: 89,
    image: 'food/papaya.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },{
    id: 18,
    title: 'Avacado',
    category: 'Fruits',
    price: 30,
    image: 'food/avacado.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },

  {
    id: 19,
    title: 'Litchi',
    category: 'Fruits',
    price: 49,
    image: 'food/lichi.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },{
    id: 20,
    title: 'Guvava',
    category: 'Fruits',
    price: 25,
    image: 'food/guvava.webp',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione, voluptas.`,
  },
];
export default menu;
